services:
  - type: web
    name: umfind
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_NAME
        value: UMFind
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        value: base64:p34gk8MfWmAaNX+T+NW1mATX/oLGU1RVRujGfPdXsxc=
      - key: APP_URL
        value: https://umfind-lost-and-found-system.onrender.com
      - key: SESSION_DRIVER
        value: file
      - key: SESSION_LIFETIME
        value: 120
      - key: SESSION_ENCRYPT
        value: false
      - key: SESSION_PATH
        value: /
      - key: SESSION_DOMAIN
        value: ""
      - key: SESSION_SECURE_COOKIE
        value: true
      - key: SESSION_SAME_SITE
        value: lax
      - key: CACHE_STORE
        value: file
      - key: FILESYSTEM_DISK
        value: public
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: QUEUE_CONNECTION
        value: sync
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_LEVEL
        value: error